#+title: Change log of the Ef Themes
#+author: Protesilaos Stavrou
#+email: info@protesilaos.com
#+options: ':nil toc:nil num:nil author:nil email:nil

This document contains the release notes for each tagged commit on the
project's main git repository: <https://git.sr.ht/~protesilaos/ef-themes>.

The newest release is at the top.  For further details, please consult
the manual: <https://protesilaos.com/emacs/ef-themes>.

* Version 0.5.0 on 2022-09-11
:PROPERTIES:
:CUSTOM_ID: h:d0d24c93-7954-4c52-b5a2-79089b53c767
:END:

** New duo-chrome themes
:PROPERTIES:
:CUSTOM_ID: h:dfdea23c-8d89-4461-8668-04a317fb498d
:END:

The collection now includes two items which apply shades of blue and
yellow in most interfaces.  The themes are named ~ef-duo-dark~ and
~ef-duo-light~.

Read the announcement:
<https://protesilaos.com/codelog/2022-09-06-ef-themes-duo/>.

View all image samples:
<https://protesilaos.com/emacs/ef-themes-pictures>.

The choice of blue and yellow is largely stylistic: it is not done to
accommodate users with red-green colour deficiency.  For that case, the
Ef themes provide ~ef-deuteranopia-dark~ and ~ef-deuteranopia-light~.

** Bespoke accent colours for the mode line
:PROPERTIES:
:CUSTOM_ID: h:db9d8e1d-d33c-46a5-b41c-8bbb19e0b8af
:END:

Each theme now includes a subset of foreground values optimised for use
against the active mode line's background.  The active mode line's
background is accented, meaning that we cannot use colours that are
otherwise decent against the main background.

These new entries are meant to style warnings, errors, and other
notifications that appear on the mode line.  They empower us to extend
support for packages that make use of such colour-coding (more further
below).

** "Subtle" accented backgrounds
:PROPERTIES:
:CUSTOM_ID: h:1935e028-10ea-4a3f-adb5-a755c1ddfe2b
:END:

Each theme's palette now contains six accented backgrounds that are not
very intense.  These are used by packages that need to (i) highlight a
line or region, (ii) preserve a modicum of legibility without overriding
existing foreground values (more below about new packages).

** Refined the colour of prompts, where necessary
:PROPERTIES:
:CUSTOM_ID: h:5a1f7bde-658a-4240-bab8-92cb8e5327b0
:END:

Each theme's palette now includes a dedicated =prompt= mapping.  This
gives us full control over what colour we use for prompts.  In some
themes the prompt will look the same as before, though I made a few
changes to have stylistic consistency in each theme.  Specifically:

| Theme                 | Old prompt   | New prompt     |
|-----------------------+--------------+----------------|
| ef-deuteranopia-dark  | cyan-warmer  | yellow         |
| ef-deuteranopia-light | cyan         | blue           |
| ef-duo-dark           | green-cooler | yellow         |
| ef-duo-light          | green-cooler | blue           |
| ef-spring             | blue         | green          |
| ef-summer             | cyan-cooler  | magenta-warmer |
| ef-winter             | green-cooler | magenta-warmer |

In short: we don't want prompts to look blue/green all the time.  Some
themes have a different character.

** Newly supported packages
:PROPERTIES:
:CUSTOM_ID: h:197a98a6-96d3-47ca-935d-6736d3836211
:END:

In general, if a package does not look right, it is not supported by the
Ef themes.  What we have for this release:

+ auctex :: Thanks to Philip Kaludercic for providing the sample file
  that let me view the relevant faces, as well as for helping me
  correct some mistakes of mine:
  <https://lists.sr.ht/~protesilaos/ef-themes/%3C87h71t97hl.fsf%40posteo.net%3E>.

+ company :: Thanks to Alan Schmitt for reminding me about it:
  <https://lists.sr.ht/~protesilaos/ef-themes/%3C87pmgjw3j9.fsf%40m4x.org%3E>.

+ dirvish :: Thanks to Alex Lu (=dirvish= developer) for the
  contribution.  This was done in pull request 14 at the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/pull/14>.  The change is
  below the ~15 line threshold and thus does not require copyright
  assignment to the Free Software Foundation.

+ doom-modeline :: Expanded support for almost all the faces it
  provides.  The only exception is some debugging-related indicators
  that I do not know how to trigger (contact me, if you encounter them).
  This support is made possible by the new accented foregrounds that are
  designed specifically for the mode line.

+ gnus :: Expanded support for all the faces it defines.  I had used
  Gnus for several months before and am familiar with its interfaces.
  Though I never made use of its scoring system.  I think the relevant
  faces look okay, though please let me know if we can refine them
  further.

+ image-dired :: This is made possible by the new "subtle" coloured
  backgrounds that I added to each theme.

+ lin (my package) :: Made possible by the new subtle backgrounds.

+ pulsar (my package) :: Same as above.

+ pulse :: Same.

+ recursion-indicator :: Same

+ selectrum :: Made it look like the already supported =vertico=.

+ tempel :: Same as =lin= and friends.

** Refinements to existing faces
:PROPERTIES:
:CUSTOM_ID: h:83fa9e74-0460-49b0-a123-15767d07f806
:END:

+ Lots of small tweaks affect mode line indicators, per the new
  foreground colours I introduced.  Expect to see a bit more colour in
  the mode line when using =magit=, compilation buffers, appointment
  reminders, keyboard macros, Org agenda filters, and more.

+ All the =rcirc= faces have been revised in the interest of thematic
  consistency.

  - Rcirc uses the new foregrounds for the mode line, where relevant.

  - Indicators that track/highlight the user's nick use the same
    paradigm.

  - IRC server messages look like comments in code buffers.

  Thanks to Philip Kaludercic for telling me about the downsides of
  using the ~italic~ in the ~rcirc-nick-in-message-full-line~ face:
  <https://lists.sr.ht/~protesilaos/ef-themes/%3C87edwphahl.fsf%40posteo.net%3E>.

  Please note that I am not a regular/experienced IRC user.  If there
  are improvements to be made, I am happy to implement them but will
  likely need your help (I will ask the relevant questions).

** New fallback behaviour for ~ef-themes-toggle~
:PROPERTIES:
:CUSTOM_ID: h:3399f33c-3d1b-4d18-b50f-8d2f0838aa54
:END:

The command ~ef-themes-toggle~ will switch between two themes specified
in the user option ~ef-themes-to-toggle~.  For example:

#+begin_src emacs-lisp
;; Toggle between `ef-summer' and `ef-winter' using `ef-themes-toggle'.
(setq ef-themes-to-toggle '(ef-summer ef-winter))
#+end_src

By default, ~ef-themes-to-toggle~ is nil. In the past, this meant that
~ef-themes-toggle~ would do nothing out-of-the-box.  To improve the
initial user experience, the command will now fall back to minibuffer
completion to load a theme if ~ef-themes-to-toggle~ does not have the
expected value.  The completion candidates are the items of the Ef
themes collection.  This fallback behaviour is essentially the same as
what the user gets by invoking the ~ef-themes-select~ command.

When ~ef-themes-to-toggle~ is set properly, the corresponding command
will perform the switch, as intended.

This is based on the discussion with Philip Kaludercic about revising
the ~ef-themes-toggle~ command to have a more Do-What-I-Mean behaviour:
<https://lists.sr.ht/~protesilaos/ef-themes/%3C878rmwfs0e.fsf%40posteo.net%3E>.

** Improved how ~ef-themes-load-random~ picks subsets
:PROPERTIES:
:CUSTOM_ID: h:4407d5a6-b837-4168-88b2-f7b175978122
:END:

The ~ef-themes-load-random~ command accepts a prefix argument (=C-u=, by
default): it prompts the user for a =dark= or =light= subset out of the
collection.  Once that is selected, the command loads a theme at random.

Before, the prompt was using minibuffer completion, but this has now
changed to a ~read-multiple-choice~ function, meaning that =d= selects
=dark= and =l= selects =light=.  Basically, we skip possible extra key
presses.

Thanks to Philip Kaludercic for the patch:
<https://lists.sr.ht/~protesilaos/ef-themes/patches/35089>.

** Internal changes
:PROPERTIES:
:CUSTOM_ID: h:b9156099-0bcd-4974-9cdf-ada73d5745ce
:END:

+ Fixed the initial colors' list in the ~ef-themes-with-colors~ macro.
  Thanks to Steve Molitor for telling me that the previous design would
  not work if ~ef-light~ was not loaded.  This was done in issue 11 at
  the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/11>.

+ Simplified the helper function ~ef-themes--current-theme~.  Thanks to
  Jonas Collberg for the feedback in issue 12 over at the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/12>.  Also thanks to
  Jonas for the subsequent patch in pull request 13:
  <https://github.com/protesilaos/ef-themes/pull/13>.  The change is
  below the ~15 line threshold and thus does not require copyright
  assignment to the Free Software Foundation.

+ Refined the colour mapping of some themes to improve overall
  aesthetics and/or usability, without deviating from the theme's
  established character.  For example, in the ~ef-dark~ I adjusted the
  mappings for dates, links, and names.  This helps distinguish all
  elements, while retaining the overall looks of the design.  Some
  contexts where that is relevant:

  - Notmuch search buffers
  - Magit commit log
  - Org clocktables
  - Org documents with links, to-do, etc.

  I will not cover all such technicalities.  Please consult the Git
  commit log.  If, however, some new combination of colours feels
  awkward, you are welcome to tell me about it.

+ Made improvements to the manual and implemented other internal
  changes.

* Version 0.4.0 on 2022-08-29
:PROPERTIES:
:CUSTOM_ID: h:cc22cc5a-d787-4335-abf0-aa45cef92721
:END:

** New deuteranopia-friendly themes
:PROPERTIES:
:CUSTOM_ID: h:f94f8637-73c8-4e43-bc70-c17c42e76ad6
:END:

Designed two bespoke themes for users with red-green colour deficiency
or blindness (deuteranopia).  They rely on blue and yellow hues.  Their
names are:

+ ~ef-deuteranopia-dark~
+ ~ef-deuteranopia-light~

Announcement with sample pictures:
<https://protesilaos.com/codelog/2022-08-19-ef-themes-deuteranopia/>.

** User options
:PROPERTIES:
:CUSTOM_ID: h:3dc43b00-843b-4827-b7cd-f381de619433
:END:

+ Introduced the variable ~ef-themes-mixed-fonts~.  When it is set to a
  non-nil (=t=) value, it makes spacing-sensitive elements use a
  monospaced font.  For example, Org tables and code blocks will always
  look properly aligned.  This is useful for those who either use a
  proportionately spaced font as their default or enable the built-in
  ~variable-pitch-mode~.

+ Implemented the variable ~ef-themes-variable-pitch-ui~.  When it is
  set to a non-nil (=t=) value, it renders the mode-line, tab-bar-mode,
  and tab-line-mode in a proportionately spaced font.

User options must be set before the theme is loaded.  If an option
changes, its value will be read upon a theme re-load.

For font configurations, refer to my =fontaine= package.

** Newly supported packages
:PROPERTIES:
:CUSTOM_ID: h:c1d351ca-1802-44b1-b43f-f9d5f7ba95d9
:END:

Built into Emacs:

+ eww
+ shell-script-mode (sh-mode)
+ shr

External packages:

+ consult
+ embark

** Refinements to faces
:PROPERTIES:
:CUSTOM_ID: h:582dea7b-454a-4500-871b-4ec45e875274
:END:

+ Fixed the scaling of current line of ~display-line-numbers-mode~ when
  ~text-scale-adjust~ was invoked.  Basically I forgot to include the
  ~line-number~ face, while all others were covered.  Thanks to Anthony
  Chavez for the feedback in issue 7 over at the GitHub mirror:
  <https://github.com/protesilaos/denote/issues/7>.

+ Covered all faces that define group titles in completion contexts.
  These are headings which are used by various commands, such as
  ~consult-buffer~, ~consult-imenu~, and ~consult-grep~.  As they denote
  a group name, we apply the =name= colour mapping (the hue differs for
  each theme).  And since they are titles, we inherit from ~bold~ to
  make them look like headings.  Thanks to Summer Emacs for the feedback
  which amounted to:

  1. Treating group titles as headings.
  2. Using a more consistent colour theme-wide.

+ Revised the ~compilation-info~ face from a colour-coded "success" face
  to a value that is consistent with the semantics of its application in
  file names or related (as seen in the emacs.git repository).  For
  example, file names in Grep or Xref buffers will now look like they
  belong to the theme, whereas before they were predominantly green,
  even when that did not make sense.  This point is connected to the
  above, such as in workflows that go from the minibuffer to a Grep
  buffer (e.g. with the use of the =embark= package).

+ Toned down the vertical border between windows by explicitly
  supporting the ~vertical-border~ face.  The previous design would use
  the main foreground which generally led to a disproportionately
  intense result.

+ Adjusted all spacing-sensitive faces to accommodate the user option
  ~ef-themes-mixed-fonts~, as noted above.  Also thanks to Christopher
  League for spotting that I had missed the ~line-number~ face and for
  providing the relevant patch (I do the same in the =modus-themes=):
  https://lists.sr.ht/~protesilaos/ef-themes/%3C871qt2x4wi.fsf%40nita.mail-host-address-is-not-set%3E

  The patch is well below the ~15 line threshold and thus does not
  require copyright assignment to the Free Software Foundation.

+ Enforced mono spacing for the ~org-indent~ face.  This is essential
  for ~org-indent-mode~ to align entries correctly.  Thanks to Steve
  Molitor for reporting this in the issue 9 over at the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/9>.  Steve tested a
  sample file with ~modus-vivendi~ and got the desired results.  It
  reminded me how I handle this face in the =modus-themes=.

+ Added explicit support for the ~bold~ and ~italic~ faces.  The default
  definition of ~italic~ has conditionality which we do not want, such
  as drawing an underline if the font does not have italics (e.g. Fira
  Code).  Styling it at the theme level prevents that from happening:
  the font without italics will simply use the upright/roman glyphs.
  Adding ~bold~ is just for clarity.  Its default definition is fine.

+ Made the tabs of the built-in ~tab-bar-mode~ and ~tab-line-mode~ stand
  out more.  The difference between the current tab and the rest was too
  subtle.  Depending on the lighting conditions, their respective
  backgrounds were indistinguishable.  Thanks to Summer Emacs for
  reporting this issue and for helping me decide on the final design.

+ Applied tinted backgrounds to values and arguments in transient.el
  buffers (e.g. Magit).  They now stand out better.

** Documentation
:PROPERTIES:
:CUSTOM_ID: h:5549f628-390d-478c-b8d3-a0b068f3f1e0
:END:

+ Created a page with screenshots of all the Ef themes:
  <https://protesilaos.com/emacs/ef-themes-pictures>.

+ Answered the Frequently Asked Question of letting Org tags inherit the
  foreground colour of the heading they belong to.  The gist (though
  note that the entry also mentions the option for the non-alignment of
  tags):

  #+begin_quote
  Upstream Org defines tags in headings to have the same color as the rest
  of the heading's text.  However, tags are a distinct component of the
  heading as noted in the doc string of the ~org-get-heading~ function.
  Tags also are functionally different than the ordinary text of the
  heading: they are a clickable link/button.  It thus is a matter of
  usability to render this distinction clear at the visual level: I do not
  agree with upstream Org's design decision.
  #+end_quote

+ Addressed another Frequently Asked Question on whether we can have
  Ef-style themes inspired by the Nord or Zenburn themes.  The short
  version is that this is technically difficult and undesirable.  Each
  palette in the Ef themes collection is original and is designed around
  the normative and aesthetic principles of this project.

+ Wrote an entire section on Do-It-Yourself customisations.  These
  generally are for advanced users, though the manual provides concrete
  examples of using the ~ef-themes-with-colors~ macro in tandem with the
  ~ef-themes-post-load-hook~.

+ Elaborated on the list of packages that I will most likely NOT support
  in the Ef themes.  The reasons vary though.  Quote:

  #+begin_quote
  These are difficult to support due to their (i) incompatibility with
  the design of the =ef-themes=, (ii) complexity or multiple points of
  entry, (iii) external dependencies, (iv) existence of better
  alternatives in my opinion, or (v) inconsiderate use of color
  out-of-the-box and implicit unwillingness to be good Emacs citizens
  #+end_quote

  If a certain package does not look right, then it is not supported
  (yet).

The manual can be read from Emacs, if the =ef-themes= package is
installed.  Evaluate:

#+begin_src emacs-lisp
(info "(ef-themes) Top")
#+end_src

Else visit: <https://protesilaos.com/emacs/ef-themes>.

** Internal refinements
:PROPERTIES:
:CUSTOM_ID: h:4013a8aa-d2ff-45a1-95db-edd140e31cb1
:END:

+ Recalibrated diff colours or the context of diff buffers, especially
  in Magit, to improve usability.

+ Adjusted or otherwise tweaked the hues that apply to key bindings and
  links in order to reinforce the stylistic consistency of each theme.

+ Introduced a yellow-tinted background which is used in various
  contexts that (i) should be styled with a coloured background but (ii)
  should not be colour-coded as either red or green/blue.

+ Made the ~ef-themes-with-colors~ macro always reify the current Ef
  theme's palette.  This macro is for advanced users.  Its utility is
  documented in the themes' manual.

+ Fixed how themes become "known" at startup.  Before, they were not
  registered correctly for immediate use with the ~ef-themes-select~
  command.  Thanks to Jean-Philippe Gagné Guay for the feedback in issue
  6 over at the GitHub mirror: <https://github.com/protesilaos/denote/issues/6>.

+ Tweaked some face attributes to work with Emacs 27.

+ Tinkered with the colour mapping or precise values of practically all
  the themes.  Better consult the Git log for the minutiae.  I think the
  identity of each theme is largely defined, though there may still be
  tweaks to be done here and there until we eventually reach version
  =1.0.0=.

* Version 0.3.0 on 2022-08-20
:PROPERTIES:
:CUSTOM_ID: h:f91c2c29-cc5b-4cf3-a322-f3a286a17e8c
:END:

** User-facing changes
:PROPERTIES:
:CUSTOM_ID: h:691f108f-7a92-47a9-a3a3-89c31916d8c8
:END:

+ Revised the minimum Emacs version of the =ef-themes= package.  It now
  depends on Emacs 27.1 instead of Emacs 28.1.  Relevant internal
  adjustments were made, some of which are courtesy of Philip
  Kaludercic: <https://lists.sr.ht/~protesilaos/ef-themes/patches/34787>.

  [ Philip has assigned copyright to the Free Software Foundation.  This
    is necessary for all non-trivial patches. ]

+ Added two new themes to the collection which are designed for users
  with red-green colour deficiency/blindness (deuteranopia).  In simple
  terms, their effective palette consists of blue, yellow, and the base
  tones.  The themes are named descriptively: ~ef-deuteranopia-dark~ and
  ~ef-deuteranopia-light~.  Announcement with screenshots:
  <https://protesilaos.com/codelog/2022-08-19-ef-themes-deuteranopia/>.

+ Reconsidered the principle of what kind of user options are
  acceptable.  Those which affect colours directly will never be a part
  of the project.  Others are subject to consideration with a preference
  for simplicity.  Detailed documentation to do-it-yourself will still
  be preferred over user options.

+ Implemented the ~ef-themes-headings~ user option which provides the
  mechanism to change the weight and height of each heading level, as
  well as set it to ~variable-pitch~ (i.e. a proportionately spaced
  font).  The doc string of that variable or the relevant entry in the
  manual explain the particularities and provided code samples.

  To accommodate this variable, the default style of all headings has
  been revised to remove the added height they once had.  Users who
  preferred the previous style must add the following to their
  configuration BEFORE the code that actually loads the theme (e.g. a
  ~load-theme~ call):

  #+begin_src emacs-lisp
  ;; Restore height of each heading level to its previous value.
  (setq ef-themes-headings
        '((0 . (1.9))
          (1 . (1.8))
          (2 . (1.7))
          (3 . (1.6))
          (4 . (1.5))
          (5 . (1.4))
          (6 . (1.3))
          (7 . (1.2))
          (t . (1.1))))

  ;; First set the above configuration, then load the theme (changes to
  ;; user options require a theme re-load).
  (load-theme 'ef-summer :no-confirm)
  #+end_src

+ Introduced the command ~ef-themes-toggle~ and the companion user
  option ~ef-themes-to-toggle~.  To use the command, one must first set
  their two preferred Ef themes, such as with this:

  #+begin_src emacs-lisp
  (setq ef-themes-to-toggle '(ef-summer ef-winter))
  #+end_src

  The names of all the themes are included in the ~ef-themes-collection~
  variable.  Though recall that the commands ~ef-themes-select~ and
  ~ef-themes-load-random~ still use the entire collection (read their
  doc strings or consult the manual).

+ Fixed how themes are made available at startup.  Before, there was a
  mistake to how items were registered as "known" and were thus not
  recognised by our commands, even though the standard ~load-theme~
  worked as expected.  Thanks to Iris Garcia for reporting the problem
  in issue 2 on the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/2>.  It was
  propagated to users as version 0.2.1 of the =ef-themes=.

+ Added support for these packages:

  - chart
  - doom-modeline (tentative)
  - info
  - org-habit
  - rcirc
  - smerge

  Thanks to Spike-Leung for reminding me about ~org-habit~ in issue 5
  over at the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/5>.

  [ Remember that if a package looks awfully out of place, it is not
    support (yet). ]

+ Expanded and/or clarified the manual, including an answer to the
  question of what "Ef" means:

  #+begin_quote
  "Ef" is a Greek word (ευ), commonly used as a prefix to denote that
  something is good, nice, and/or easy.  For example, eftopia (ευτοπία)
  is the opposite of dystopia (δυστοπία): a good place as opposed to a
  bad place.
  #+end_quote

+ Helped Adam Sherwood figure out why zsh-autosuggestions did not look
  right.  In short: this has nothing to do with Emacs.  Try to avoid
  termcolor{0,7,8,15} as a default.  Prefer the remaining nominal accent
  colours, as every theme is more likely to work with those, whereas,
  say, termcolor0 ("black") will not be legible with dark themes.  This
  was done in issue 3 on the GitHub mirror:
  <https://github.com/protesilaos/ef-themes/issues/3>.

** Internal refinements
:PROPERTIES:
:CUSTOM_ID: h:bf3fcbee-9057-497a-8258-2ef8029a3459
:END:

+ Recalibrated lots of colour values and mappings across several themes.
  The changes are small and help with the internal consistency of each
  theme.  Consult the Git commit log for the minutiae.

+ The internal faces for headings are now done with a ~dotimes~ call on
  ~custom-declare-face~ instead of a bespoke macro.  Thanks to Philip
  Kaludercic for the patch:
  <https://lists.sr.ht/~protesilaos/ef-themes/patches/34791>.

+ Applied ~file-equal-p~ for the registration of the themes in the
  relevant path.  Doing so is generally more resilient than ~equal~ and
  might avoid an unexpected edge case in the future.  Thanks to Philip
  Kaludercic for the patch:
  <https://lists.sr.ht/~protesilaos/ef-themes/patches/34789>.

+ Opted for ={if,when}-let*= over ={if,when}-let=.  The former do not
  support the obsolete single-binding syntax, and make clear that both
  macros operate more like ~let*~ than ~let~ by evaluating and binding
  variables sequentially.  Thanks to Philip Kaludercic for the patch:
  <https://lists.sr.ht/~protesilaos/ef-themes/patches/34787>.

** Acknowledgement for the first version of the project
:PROPERTIES:
:CUSTOM_ID: h:f7b55da3-a848-463c-ab71-aa044ee7a8dd
:END:

Thanks to user Summer Emacs whose feedback helped define the identity of
the ~ef-summer~ theme.  Summer's comments pertained to the need to
increase the occurence of yellow as the theme used to be predominantly
magenta and purple.  I thus implemented the revised colour mapping and
made the relevant adjustments.  Without Summer's comments, ~ef-summer~
wouldn't have been as pretty.

* Version 0.2.0 on 2022-08-18
:PROPERTIES:
:CUSTOM_ID: h:1e875631-853a-4bd1-9a33-ff4e51fe7614
:END:

[ Added after the fact on 2022-08-20 ]

No release notes were produced at the time.  This version included
various stylistic refinements and added commands for (i) loading a theme
and (ii) previewing a theme's colour palette.

The commands which load a theme call the =ef-themes-post-load-hook=.
Advanced and/or do-it-yourself users may have a use for it.  The manual
will eventually provide specific code samples.

* Version 0.1.0 on 2022-08-17
:PROPERTIES:
:CUSTOM_ID: h:fb284e98-ec9c-434d-9e9a-1773300d2fb6
:END:

[ Added after the fact on 2022-08-20 ]

There were no release notes for it.  It established the foundations of
the project: the main macros, the character of each theme, etc.  Check
the Git commit log for more.
