#+title: ef-themes: colorful and legible themes
#+author: Protesilaos Stavrou
#+email: info@protesilaos.com
#+language: en
#+options: ':t toc:nil author:t email:t num:t
#+startup: content
#+macro: stable-version 2.0.0
#+macro: release-date 2025-11-09
#+macro: development-version 2.1.0-dev
#+export_file_name: ef-themes.texi
#+texinfo_filename: ef-themes.info
#+texinfo_dir_category: Emacs misc features
#+texinfo_dir_title: Ef-Themes: (ef-themes)
#+texinfo_dir_desc: Colorful and legible themes
#+texinfo_header: @set MAINTAINERSITE @uref{https://protesilaos.com,maintainer webpage}
#+texinfo_header: @set MAINTAINER Protesilaos Stavrou
#+texinfo_header: @set MAINTAINEREMAIL @email{info@protesilaos.com}
#+texinfo_header: @set MAINTAINERCONTACT @uref{mailto:info@protesilaos.com,contact the maintainer}

#+texinfo: @insertcopying

This manual, written by Protesilaos Stavrou, describes the Emacs package
called ~ef-themes~, and provides every other piece of information
pertinent to it.

The documentation furnished herein corresponds to stable version
{{{stable-version}}}, released on {{{release-date}}}.  Any reference to
a newer feature which does not yet form part of the latest tagged
commit, is explicitly marked as such.

Current development target is {{{development-version}}}.

+ Package name (GNU ELPA): ~ef-themes~
+ Official manual: <https://protesilaos.com/emacs/ef-themes>
+ Change log: <https://protesilaos.com/emacs/ef-themes-changelog>
+ Sample pictures: <https://protesilaos.com/emacs/ef-themes-pictures>
+ Git repositories:
  + GitHub: <https://github.com/protesilaos/ef-themes>
  + GitLab: <https://gitlab.com/protesilaos/ef-themes>
+ Backronym: Eclectic Fashion in Themes Hides Exaggerated Markings,
  Embellishments, and Sparkles.

If you are viewing the README.org version of this file, please note that
the GNU ELPA machinery automatically generates an Info manual out of it.

#+toc: headlines 8 insert TOC here, with eight headline levels

* COPYING
:PROPERTIES:
:COPYING: t
:CUSTOM_ID: h:1d213fed-b9a9-401c-9b5d-c7df602c2f63
:END:

Copyright (C) 2022-2025  Free Software Foundation, Inc.

#+begin_quote
Permission is granted to copy, distribute and/or modify this document
under the terms of the GNU Free Documentation License, Version 1.3 or
any later version published by the Free Software Foundation; with no
Invariant Sections, with the Front-Cover Texts being “A GNU Manual,” and
with the Back-Cover Texts as in (a) below.  A copy of the license is
included in the section entitled “GNU Free Documentation License.”

(a) The FSF’s Back-Cover Text is: “You have the freedom to copy and
modify this GNU manual.”
#+end_quote

* Installation
:PROPERTIES:
:CUSTOM_ID: h:dd9e06f2-eef0-4afe-8a12-b7af5d597108
:END:
#+cindex: Installation instructions

** GNU ELPA package
:PROPERTIES:
:CUSTOM_ID: h:400d57a6-3a66-4ebf-b2e1-58a42237e0c2
:END:

The package is available as ~ef-themes~.  Simply do:

: M-x package-refresh-contents
: M-x package-install

And search for it.

GNU ELPA provides the latest stable release.  Those who prefer to follow
the development process in order to report bugs or suggest changes, can
use the version of the package from the GNU-devel ELPA archive.  Read:
https://protesilaos.com/codelog/2022-05-13-emacs-elpa-devel/.

** Manual installation
:PROPERTIES:
:CUSTOM_ID: h:97fcd2cf-a80b-4a52-a8c7-40b65e563c70
:END:

Assuming your Emacs files are found in =~/.emacs.d/=, execute the
following commands in a shell prompt:

#+begin_src sh
cd ~/.emacs.d

# Create a directory for manually-installed packages
mkdir manual-packages

# Go to the new directory
cd manual-packages

# Clone this repo, naming it "ef-themes"
git clone https://github.com/protesilaos/ef-themes ef-themes
#+end_src

Finally, in your =init.el= (or equivalent) evaluate this:

#+begin_src emacs-lisp
;; Make Elisp files in that directory available to the user.
(add-to-list 'load-path "~/.emacs.d/manual-packages/ef-themes")
#+end_src

Everything is in place to set up the package.

* Sample configuration
:PROPERTIES:
:CUSTOM_ID: h:ac76ded0-af9b-4566-aff9-75142ef2d4ef
:END:

Starting with version =2.0.0=, the ~ef-themes~ are built on top of the
~modus-themes~. This means that all customisation is done via the
Modus user options ([[#h:db8ba158-22f6-49f7-b2f2-1c8162e690dd][Customisation options]]). Furthermore, all
theme-loading commands are those of Modus ([[#h:6585235a-5219-4f78-9dd5-6a64d87d1b6e][Working with other Modus themes or taking over Modus]]).

#+begin_src emacs-lisp
(use-package ef-themes
  :ensure t
  :init
  ;; This makes the Modus commands listed below consider only the Ef
  ;; themes.  For an alternative that includes Modus and all
  ;; derivative themes (like Ef), enable the
  ;; `modus-themes-include-derivatives-mode' instead.  The manual of
  ;; the Ef themes has a section that explains all the possibilities:
  ;;
  ;; - Evaluate `(info "(ef-themes) Working with other Modus themes or taking over Modus")'
  ;; - Visit <https://protesilaos.com/emacs/ef-themes#h:6585235a-5219-4f78-9dd5-6a64d87d1b6e>
  (ef-themes-take-over-modus-themes-mode 1)
  :bind
  (("<f5>" . modus-themes-rotate)
   ("C-<f5>" . modus-themes-select)
   ("M-<f5>" . modus-themes-load-random))
  :config
  ;; All customisations here.
  (setq modus-themes-mixed-fonts t)
  (setq modus-themes-italic-constructs t)

  ;; Finally, load your theme of choice (or a random one with
  ;; `modus-themes-load-random', `modus-themes-load-random-dark',
  ;; `modus-themes-load-random-light').
  (modus-themes-load-theme 'ef-summer))
#+end_src

* Working with other Modus themes or taking over Modus
:PROPERTIES:
:CUSTOM_ID: h:6585235a-5219-4f78-9dd5-6a64d87d1b6e
:END:

Starting version =2.0.0=, the Ef themes are built on top of the Modus
themes. This means that they inherit the comprehensive infrastructure
of Modus and all of its wide face/package coverage. To make the change
easier for existing users, we provide aliases for user options and
commands.

** Loading only Ef themes with the convenience wrappers we provide
:PROPERTIES:
:CUSTOM_ID: h:95df9646-b8dc-4c44-a582-9ba01e561b59
:END:

All the old commands Ef provided for loading one of its themes will
still work as before, meaning that they will only ever show and load a
theme that belongs to the Ef collection ([[#h:6c8abcaf-c0fa-4fb1-a9c0-f1dcf71c7d73][Combining core Modus themes with all their derivatives]]).

Internally, these commands are now using the Modus infrastructure and
are then limiting the set of themes to the Ef collection. They are
thus convenience wrappers around the equivalent Modus commands.

#+findex: ef-themes-toggle
- ~ef-themes-toggle~

#+findex: ef-themes-rotate
- ~ef-themes-rotate~

#+findex: ef-themes-select
- ~ef-themes-select~

#+findex: ef-themes-load-random
- ~ef-themes-load-random~

#+findex: ef-themes-load-random-dark
- ~ef-themes-load-random-dark~

#+findex: ef-themes-load-random-light
- ~ef-themes-load-random-light~

#+findex: ef-themes-list-colors
#+findex: ef-themes-list-colors-current
Additionally, the commands ~ef-themes-list-colors~ and
~ef-themes-list-colors-current~ use the relevant Modus functionality
under the hood while working only with Ef themes.

Depending on their needs, users may prefer to take over Modus
completely, instead of relying on these convenience wrapper commands
([[#h:86bbfef9-2a34-44fb-abdc-f384882f6a42][Taking over the Modus commands altogether]]).

** Combining core Modus themes with all their derivatives
:PROPERTIES:
:CUSTOM_ID: h:6c8abcaf-c0fa-4fb1-a9c0-f1dcf71c7d73
:END:

#+findex: modus-themes-include-derivatives-mode
The minor mode ~modus-themes-include-derivatives-mode~ makes all the
theme-loading commands that Modus defines consider all core and
derivative themes. This means that something like ~modus-themes-select~
will offer ~modus-operandi~ and ~ef-summer~ as two of the many
possible candidates.

In this scenario, the Modus and Ef collections become part of a larger
family of themes as opposed to only considering one or the other
([[#h:95df9646-b8dc-4c44-a582-9ba01e561b59][Loading only Ef themes with the convenience wrappers we provide]]).
Enable ~modus-themes-include-derivatives-mode~ and then access them
all with the following commands:

#+findex: modus-themes-toggle
- ~modus-themes-toggle~

#+findex: modus-themes-rotate
- ~modus-themes-rotate~

#+findex: modus-themes-select
- ~modus-themes-select~

#+findex: modus-themes-load-random
- ~modus-themes-load-random~

#+findex: modus-themes-load-random-dark
- ~modus-themes-load-random-dark~

#+findex: modus-themes-load-random-light
- ~modus-themes-load-random-light~

#+findex: modus-themes-list-colors
#+findex: modus-themes-preview-colors
- ~modus-themes-list-colors~ (alias ~modus-themes-preview-colors~)

#+findex: modus-themes-list-colors-current
- ~modus-themes-list-colors-current~ (alias ~modus-themes-preview-colors-current~)

Consult the manual of the Modus themes for further details and/or read
the documentation string of each command. Evaluate ~(info "(modus-themes) Top")~
or visit <https://protesilaos.com/emacs/modus-themes>.

** Taking over the Modus commands altogether
:PROPERTIES:
:CUSTOM_ID: h:86bbfef9-2a34-44fb-abdc-f384882f6a42
:END:

#+findex: ef-themes-take-over-modus-themes-mode
The minor mode ~ef-themes-take-over-modus-themes-mode~ makes all Modus
commands that load a theme consider only Ef themes. This is the
opposite of allowing different theme collections to be blended
together ([[#h:6c8abcaf-c0fa-4fb1-a9c0-f1dcf71c7d73][Combining core Modus themes with all their derivatives]]).
It effectively is the same as using one of the convenience wrapper
commands we already provide ([[#h:95df9646-b8dc-4c44-a582-9ba01e561b59][Loading only Ef themes with the convenience wrappers we provide]]).

This minor mode exists to accommodate the needs of users who install
both the Modus and Ef theme packages (and possibly other Modus
derivatives). They can maintain a single/shared configuration and then
decide when to enable ~ef-themes-take-over-modus-themes-mode~ to
switch to using just the Ef themes. In this scenario, a key binding
to, say, ~modus-themes-rotate~ does not need to be updated: it
internally reads only Ef themes. When ~ef-themes-take-over-modus-themes-mode~
is disabled, that same key binding will revert to doing what it did
before (load only a core Modus theme or Modus plus derivatives if
~modus-themes-include-derivatives-mode~ is enabled).

** Customisation options for compatibility with Modus
:PROPERTIES:
:CUSTOM_ID: h:db8ba158-22f6-49f7-b2f2-1c8162e690dd
:END:

Consult the Modus themes manual for all customisation options. All the
user options defined by the Ef themes prior to their version =2.0.0=
(i.e. before building on top of the Modus themes) are now aliases for
the equivalent Modus options. We do this for backward compatibility.
Concretely:

| Old name                           | Is alias for CURRENT NAME             |
|------------------------------------+---------------------------------------|
| ef-themes-disable-other-themes     | modus-themes-disable-other-themes     |
| ef-themes-to-toggle                | modus-themes-to-toggle                |
| ef-themes-to-rotate                | modus-themes-to-rotate                |
| ef-themes-after-load-theme-hook    | modus-themes-after-load-theme-hook    |
| ef-themes-italic-constructs        | modus-themes-italic-constructs        |
| ef-themes-bold-constructs          | modus-themes-bold-constructs          |
| ef-themes-variable-pitch-ui        | modus-themes-variable-pitch-ui        |
| ef-themes-mixed-fonts              | modus-themes-mixed-fonts              |
| ef-themes-headings                 | modus-themes-headings                 |
| ef-themes-completions              | modus-themes-completions              |
| ef-themes-prompts                  | modus-themes-prompts                  |
| ef-themes-common-palette-overrides | modus-themes-common-palette-overrides |

* Loading a theme
:PROPERTIES:
:CUSTOM_ID: h:75d74aea-d17f-497f-a3b8-f0bf4c372de0
:END:

Consult the Modus themes manual for all commands that load a theme. We
also explain the relevant commands and user options ([[#h:6585235a-5219-4f78-9dd5-6a64d87d1b6e][Working with other Modus themes or taking over Modus]]). Or
check the sample configuration to quickly get started ([[#h:ac76ded0-af9b-4566-aff9-75142ef2d4ef][Sample configuration]]).

* Acknowledgements
:PROPERTIES:
:CUSTOM_ID: h:5d8753d2-cc10-44a7-9467-dcd62157718b
:END:
#+cindex: Contributors

This project is meant to be a collective effort.  Every bit of help
matters.

+ Author/maintainer :: Protesilaos Stavrou.

+ Contributions to code or the manual :: Alex Lu, Christopher League,
  Eshel Yaron, Gautier Ponsinet, John Haman, Kevin Fleming, Oleksii
  (Alex) Koval, Leilei332, Pedro Cunha, Philip Kaludercic, Ryan
  Kaskel, Sean Devlin, Walheimat.

+ Ideas and/or user feedback :: Adam Porter (alphapapa), Alan Schmitt,
  Amo DelBello, Anthony Chavez, Benjamin (zealotrush), Bruno Boal,
  Daniel Mendler, Federico Stilman, Filippo Argiolas, Iris Garcia,
  Jean-Philippe Gagné Guay, Len Trigg, Jonas Collberg, Saša Janiška,
  Spike-Leung, Steve Molitor, Summer Emacs, Sven Seebeck, Thanos
  Apollo, Zoltán Király, goldfita, marasenna, newhallroad.

* GNU Free Documentation License
:PROPERTIES:
:CUSTOM_ID: h:a349a898-0068-4529-ab3b-167c1b7b8534
:END:

#+texinfo: @include doclicense.texi

#+begin_export html
<pre>

                GNU Free Documentation License
                 Version 1.3, 3 November 2008


 Copyright (C) 2000, 2001, 2002, 2007, 2008 Free Software Foundation, Inc.
     <https://fsf.org/>
 Everyone is permitted to copy and distribute verbatim copies
 of this license document, but changing it is not allowed.

0. PREAMBLE

The purpose of this License is to make a manual, textbook, or other
functional and useful document "free" in the sense of freedom: to
assure everyone the effective freedom to copy and redistribute it,
with or without modifying it, either commercially or noncommercially.
Secondarily, this License preserves for the author and publisher a way
to get credit for their work, while not being considered responsible
for modifications made by others.

This License is a kind of "copyleft", which means that derivative
works of the document must themselves be free in the same sense.  It
complements the GNU General Public License, which is a copyleft
license designed for free software.

We have designed this License in order to use it for manuals for free
software, because free software needs free documentation: a free
program should come with manuals providing the same freedoms that the
software does.  But this License is not limited to software manuals;
it can be used for any textual work, regardless of subject matter or
whether it is published as a printed book.  We recommend this License
principally for works whose purpose is instruction or reference.


1. APPLICABILITY AND DEFINITIONS

This License applies to any manual or other work, in any medium, that
contains a notice placed by the copyright holder saying it can be
distributed under the terms of this License.  Such a notice grants a
world-wide, royalty-free license, unlimited in duration, to use that
work under the conditions stated herein.  The "Document", below,
refers to any such manual or work.  Any member of the public is a
licensee, and is addressed as "you".  You accept the license if you
copy, modify or distribute the work in a way requiring permission
under copyright law.

A "Modified Version" of the Document means any work containing the
Document or a portion of it, either copied verbatim, or with
modifications and/or translated into another language.

A "Secondary Section" is a named appendix or a front-matter section of
the Document that deals exclusively with the relationship of the
publishers or authors of the Document to the Document's overall
subject (or to related matters) and contains nothing that could fall
directly within that overall subject.  (Thus, if the Document is in
part a textbook of mathematics, a Secondary Section may not explain
any mathematics.)  The relationship could be a matter of historical
connection with the subject or with related matters, or of legal,
commercial, philosophical, ethical or political position regarding
them.

The "Invariant Sections" are certain Secondary Sections whose titles
are designated, as being those of Invariant Sections, in the notice
that says that the Document is released under this License.  If a
section does not fit the above definition of Secondary then it is not
allowed to be designated as Invariant.  The Document may contain zero
Invariant Sections.  If the Document does not identify any Invariant
Sections then there are none.

The "Cover Texts" are certain short passages of text that are listed,
as Front-Cover Texts or Back-Cover Texts, in the notice that says that
the Document is released under this License.  A Front-Cover Text may
be at most 5 words, and a Back-Cover Text may be at most 25 words.

A "Transparent" copy of the Document means a machine-readable copy,
represented in a format whose specification is available to the
general public, that is suitable for revising the document
straightforwardly with generic text editors or (for images composed of
pixels) generic paint programs or (for drawings) some widely available
drawing editor, and that is suitable for input to text formatters or
for automatic translation to a variety of formats suitable for input
to text formatters.  A copy made in an otherwise Transparent file
format whose markup, or absence of markup, has been arranged to thwart
or discourage subsequent modification by readers is not Transparent.
An image format is not Transparent if used for any substantial amount
of text.  A copy that is not "Transparent" is called "Opaque".

Examples of suitable formats for Transparent copies include plain
ASCII without markup, Texinfo input format, LaTeX input format, SGML
or XML using a publicly available DTD, and standard-conforming simple
HTML, PostScript or PDF designed for human modification.  Examples of
transparent image formats include PNG, XCF and JPG.  Opaque formats
include proprietary formats that can be read and edited only by
proprietary word processors, SGML or XML for which the DTD and/or
processing tools are not generally available, and the
machine-generated HTML, PostScript or PDF produced by some word
processors for output purposes only.

The "Title Page" means, for a printed book, the title page itself,
plus such following pages as are needed to hold, legibly, the material
this License requires to appear in the title page.  For works in
formats which do not have any title page as such, "Title Page" means
the text near the most prominent appearance of the work's title,
preceding the beginning of the body of the text.

The "publisher" means any person or entity that distributes copies of
the Document to the public.

A section "Entitled XYZ" means a named subunit of the Document whose
title either is precisely XYZ or contains XYZ in parentheses following
text that translates XYZ in another language.  (Here XYZ stands for a
specific section name mentioned below, such as "Acknowledgements",
"Dedications", "Endorsements", or "History".)  To "Preserve the Title"
of such a section when you modify the Document means that it remains a
section "Entitled XYZ" according to this definition.

The Document may include Warranty Disclaimers next to the notice which
states that this License applies to the Document.  These Warranty
Disclaimers are considered to be included by reference in this
License, but only as regards disclaiming warranties: any other
implication that these Warranty Disclaimers may have is void and has
no effect on the meaning of this License.

2. VERBATIM COPYING

You may copy and distribute the Document in any medium, either
commercially or noncommercially, provided that this License, the
copyright notices, and the license notice saying this License applies
to the Document are reproduced in all copies, and that you add no
other conditions whatsoever to those of this License.  You may not use
technical measures to obstruct or control the reading or further
copying of the copies you make or distribute.  However, you may accept
compensation in exchange for copies.  If you distribute a large enough
number of copies you must also follow the conditions in section 3.

You may also lend copies, under the same conditions stated above, and
you may publicly display copies.


3. COPYING IN QUANTITY

If you publish printed copies (or copies in media that commonly have
printed covers) of the Document, numbering more than 100, and the
Document's license notice requires Cover Texts, you must enclose the
copies in covers that carry, clearly and legibly, all these Cover
Texts: Front-Cover Texts on the front cover, and Back-Cover Texts on
the back cover.  Both covers must also clearly and legibly identify
you as the publisher of these copies.  The front cover must present
the full title with all words of the title equally prominent and
visible.  You may add other material on the covers in addition.
Copying with changes limited to the covers, as long as they preserve
the title of the Document and satisfy these conditions, can be treated
as verbatim copying in other respects.

If the required texts for either cover are too voluminous to fit
legibly, you should put the first ones listed (as many as fit
reasonably) on the actual cover, and continue the rest onto adjacent
pages.

If you publish or distribute Opaque copies of the Document numbering
more than 100, you must either include a machine-readable Transparent
copy along with each Opaque copy, or state in or with each Opaque copy
a computer-network location from which the general network-using
public has access to download using public-standard network protocols
a complete Transparent copy of the Document, free of added material.
If you use the latter option, you must take reasonably prudent steps,
when you begin distribution of Opaque copies in quantity, to ensure
that this Transparent copy will remain thus accessible at the stated
location until at least one year after the last time you distribute an
Opaque copy (directly or through your agents or retailers) of that
edition to the public.

It is requested, but not required, that you contact the authors of the
Document well before redistributing any large number of copies, to
give them a chance to provide you with an updated version of the
Document.


4. MODIFICATIONS

You may copy and distribute a Modified Version of the Document under
the conditions of sections 2 and 3 above, provided that you release
the Modified Version under precisely this License, with the Modified
Version filling the role of the Document, thus licensing distribution
and modification of the Modified Version to whoever possesses a copy
of it.  In addition, you must do these things in the Modified Version:

A. Use in the Title Page (and on the covers, if any) a title distinct
   from that of the Document, and from those of previous versions
   (which should, if there were any, be listed in the History section
   of the Document).  You may use the same title as a previous version
   if the original publisher of that version gives permission.
B. List on the Title Page, as authors, one or more persons or entities
   responsible for authorship of the modifications in the Modified
   Version, together with at least five of the principal authors of the
   Document (all of its principal authors, if it has fewer than five),
   unless they release you from this requirement.
C. State on the Title page the name of the publisher of the
   Modified Version, as the publisher.
D. Preserve all the copyright notices of the Document.
E. Add an appropriate copyright notice for your modifications
   adjacent to the other copyright notices.
F. Include, immediately after the copyright notices, a license notice
   giving the public permission to use the Modified Version under the
   terms of this License, in the form shown in the Addendum below.
G. Preserve in that license notice the full lists of Invariant Sections
   and required Cover Texts given in the Document's license notice.
H. Include an unaltered copy of this License.
I. Preserve the section Entitled "History", Preserve its Title, and add
   to it an item stating at least the title, year, new authors, and
   publisher of the Modified Version as given on the Title Page.  If
   there is no section Entitled "History" in the Document, create one
   stating the title, year, authors, and publisher of the Document as
   given on its Title Page, then add an item describing the Modified
   Version as stated in the previous sentence.
J. Preserve the network location, if any, given in the Document for
   public access to a Transparent copy of the Document, and likewise
   the network locations given in the Document for previous versions
   it was based on.  These may be placed in the "History" section.
   You may omit a network location for a work that was published at
   least four years before the Document itself, or if the original
   publisher of the version it refers to gives permission.
K. For any section Entitled "Acknowledgements" or "Dedications",
   Preserve the Title of the section, and preserve in the section all
   the substance and tone of each of the contributor acknowledgements
   and/or dedications given therein.
L. Preserve all the Invariant Sections of the Document,
   unaltered in their text and in their titles.  Section numbers
   or the equivalent are not considered part of the section titles.
M. Delete any section Entitled "Endorsements".  Such a section
   may not be included in the Modified Version.
N. Do not retitle any existing section to be Entitled "Endorsements"
   or to conflict in title with any Invariant Section.
O. Preserve any Warranty Disclaimers.

If the Modified Version includes new front-matter sections or
appendices that qualify as Secondary Sections and contain no material
copied from the Document, you may at your option designate some or all
of these sections as invariant.  To do this, add their titles to the
list of Invariant Sections in the Modified Version's license notice.
These titles must be distinct from any other section titles.

You may add a section Entitled "Endorsements", provided it contains
nothing but endorsements of your Modified Version by various
parties--for example, statements of peer review or that the text has
been approved by an organization as the authoritative definition of a
standard.

You may add a passage of up to five words as a Front-Cover Text, and a
passage of up to 25 words as a Back-Cover Text, to the end of the list
of Cover Texts in the Modified Version.  Only one passage of
Front-Cover Text and one of Back-Cover Text may be added by (or
through arrangements made by) any one entity.  If the Document already
includes a cover text for the same cover, previously added by you or
by arrangement made by the same entity you are acting on behalf of,
you may not add another; but you may replace the old one, on explicit
permission from the previous publisher that added the old one.

The author(s) and publisher(s) of the Document do not by this License
give permission to use their names for publicity for or to assert or
imply endorsement of any Modified Version.


5. COMBINING DOCUMENTS

You may combine the Document with other documents released under this
License, under the terms defined in section 4 above for modified
versions, provided that you include in the combination all of the
Invariant Sections of all of the original documents, unmodified, and
list them all as Invariant Sections of your combined work in its
license notice, and that you preserve all their Warranty Disclaimers.

The combined work need only contain one copy of this License, and
multiple identical Invariant Sections may be replaced with a single
copy.  If there are multiple Invariant Sections with the same name but
different contents, make the title of each such section unique by
adding at the end of it, in parentheses, the name of the original
author or publisher of that section if known, or else a unique number.
Make the same adjustment to the section titles in the list of
Invariant Sections in the license notice of the combined work.

In the combination, you must combine any sections Entitled "History"
in the various original documents, forming one section Entitled
"History"; likewise combine any sections Entitled "Acknowledgements",
and any sections Entitled "Dedications".  You must delete all sections
Entitled "Endorsements".


6. COLLECTIONS OF DOCUMENTS

You may make a collection consisting of the Document and other
documents released under this License, and replace the individual
copies of this License in the various documents with a single copy
that is included in the collection, provided that you follow the rules
of this License for verbatim copying of each of the documents in all
other respects.

You may extract a single document from such a collection, and
distribute it individually under this License, provided you insert a
copy of this License into the extracted document, and follow this
License in all other respects regarding verbatim copying of that
document.


7. AGGREGATION WITH INDEPENDENT WORKS

A compilation of the Document or its derivatives with other separate
and independent documents or works, in or on a volume of a storage or
distribution medium, is called an "aggregate" if the copyright
resulting from the compilation is not used to limit the legal rights
of the compilation's users beyond what the individual works permit.
When the Document is included in an aggregate, this License does not
apply to the other works in the aggregate which are not themselves
derivative works of the Document.

If the Cover Text requirement of section 3 is applicable to these
copies of the Document, then if the Document is less than one half of
the entire aggregate, the Document's Cover Texts may be placed on
covers that bracket the Document within the aggregate, or the
electronic equivalent of covers if the Document is in electronic form.
Otherwise they must appear on printed covers that bracket the whole
aggregate.


8. TRANSLATION

Translation is considered a kind of modification, so you may
distribute translations of the Document under the terms of section 4.
Replacing Invariant Sections with translations requires special
permission from their copyright holders, but you may include
translations of some or all Invariant Sections in addition to the
original versions of these Invariant Sections.  You may include a
translation of this License, and all the license notices in the
Document, and any Warranty Disclaimers, provided that you also include
the original English version of this License and the original versions
of those notices and disclaimers.  In case of a disagreement between
the translation and the original version of this License or a notice
or disclaimer, the original version will prevail.

If a section in the Document is Entitled "Acknowledgements",
"Dedications", or "History", the requirement (section 4) to Preserve
its Title (section 1) will typically require changing the actual
title.


9. TERMINATION

You may not copy, modify, sublicense, or distribute the Document
except as expressly provided under this License.  Any attempt
otherwise to copy, modify, sublicense, or distribute it is void, and
will automatically terminate your rights under this License.

However, if you cease all violation of this License, then your license
from a particular copyright holder is reinstated (a) provisionally,
unless and until the copyright holder explicitly and finally
terminates your license, and (b) permanently, if the copyright holder
fails to notify you of the violation by some reasonable means prior to
60 days after the cessation.

Moreover, your license from a particular copyright holder is
reinstated permanently if the copyright holder notifies you of the
violation by some reasonable means, this is the first time you have
received notice of violation of this License (for any work) from that
copyright holder, and you cure the violation prior to 30 days after
your receipt of the notice.

Termination of your rights under this section does not terminate the
licenses of parties who have received copies or rights from you under
this License.  If your rights have been terminated and not permanently
reinstated, receipt of a copy of some or all of the same material does
not give you any rights to use it.


10. FUTURE REVISIONS OF THIS LICENSE

The Free Software Foundation may publish new, revised versions of the
GNU Free Documentation License from time to time.  Such new versions
will be similar in spirit to the present version, but may differ in
detail to address new problems or concerns.  See
https://www.gnu.org/licenses/.

Each version of the License is given a distinguishing version number.
If the Document specifies that a particular numbered version of this
License "or any later version" applies to it, you have the option of
following the terms and conditions either of that specified version or
of any later version that has been published (not as a draft) by the
Free Software Foundation.  If the Document does not specify a version
number of this License, you may choose any version ever published (not
as a draft) by the Free Software Foundation.  If the Document
specifies that a proxy can decide which future versions of this
License can be used, that proxy's public statement of acceptance of a
version permanently authorizes you to choose that version for the
Document.

11. RELICENSING

"Massive Multiauthor Collaboration Site" (or "MMC Site") means any
World Wide Web server that publishes copyrightable works and also
provides prominent facilities for anybody to edit those works.  A
public wiki that anybody can edit is an example of such a server.  A
"Massive Multiauthor Collaboration" (or "MMC") contained in the site
means any set of copyrightable works thus published on the MMC site.

"CC-BY-SA" means the Creative Commons Attribution-Share Alike 3.0
license published by Creative Commons Corporation, a not-for-profit
corporation with a principal place of business in San Francisco,
California, as well as future copyleft versions of that license
published by that same organization.

"Incorporate" means to publish or republish a Document, in whole or in
part, as part of another Document.

An MMC is "eligible for relicensing" if it is licensed under this
License, and if all works that were first published under this License
somewhere other than this MMC, and subsequently incorporated in whole or
in part into the MMC, (1) had no cover texts or invariant sections, and
(2) were thus incorporated prior to November 1, 2008.

The operator of an MMC Site may republish an MMC contained in the site
under CC-BY-SA on the same site at any time before August 1, 2009,
provided the MMC is eligible for relicensing.


ADDENDUM: How to use this License for your documents

To use this License in a document you have written, include a copy of
the License in the document and put the following copyright and
license notices just after the title page:

    Copyright (c)  YEAR  YOUR NAME.
    Permission is granted to copy, distribute and/or modify this document
    under the terms of the GNU Free Documentation License, Version 1.3
    or any later version published by the Free Software Foundation;
    with no Invariant Sections, no Front-Cover Texts, and no Back-Cover Texts.
    A copy of the license is included in the section entitled "GNU
    Free Documentation License".

If you have Invariant Sections, Front-Cover Texts and Back-Cover Texts,
replace the "with...Texts." line with this:

    with the Invariant Sections being LIST THEIR TITLES, with the
    Front-Cover Texts being LIST, and with the Back-Cover Texts being LIST.

If you have Invariant Sections without Cover Texts, or some other
combination of the three, merge those two alternatives to suit the
situation.

If your document contains nontrivial examples of program code, we
recommend releasing these examples in parallel under your choice of
free software license, such as the GNU General Public License,
to permit their use in free software.
</pre>
#+end_export

#+html: <!--

* Indices
:PROPERTIES:
:CUSTOM_ID: h:3dbfeab5-bf86-4dfe-bf90-74061205b570
:END:

** Function index
:PROPERTIES:
:INDEX: fn
:CUSTOM_ID: h:c3fa52c2-988f-40f2-84a8-07699a61867c
:END:

** Variable index
:PROPERTIES:
:INDEX: vr
:CUSTOM_ID: h:02b12c7b-22e5-457b-8086-5bf7866db0de
:END:

** Concept index
:PROPERTIES:
:INDEX: cp
:CUSTOM_ID: h:c68456c8-ec2b-4d16-93d2-f9fcb18b2fdd
:END:

#+html: -->
